// Gameplay tuning lives here. Keep rendering-only values in game.js.
window.YOKOSHOOT_CONFIG = {
  dialogue: {
    autoSeconds: 2.4,
    midBossExtraSeconds: 1,
  },

  player: {
    life: 5,
    maxLife: 5,
    bossDefeatLifeRecovery: 2,
    lifeWipeSeconds: 0.42,
    lifeRecoveryStepSeconds: 0.62,
    moveSpeed: 285,
    knockbackDistance: 44,
    hitInvincibleSeconds: 1.4,
    fireRatePerSecond: 6,
    knifeSpeed: 640,
    wakizashiSpeed: 560,
    wakizashiCooldownSeconds: 3,
    tachiOrbitSeconds: 2,
    tachiOrbitRadius: 54,
    tachiDashSpeed: 620,
    aimAngleDegrees: 25.714,
    upAimChainSeconds: 0.3,
    upAimAcquireAngleDegrees: 50,
    upAimHomingSeconds: 0.45,
    upAimTurnDegreesPerSecond: 140,
    upAimMaxTargetDistance: 560,
    flinchSeconds: 0.5,
    dash: {
      chargeSeconds: 1,
      speedMultiplier: 3,
      returnSpeedMultiplier: 2,
      damage: 9,
      cooldownSeconds: 4,
    },
  },

  score: {
    enemyDefeat: 100,
    humanoidFullLifeDefeat: 1000,
  },

  stages: {
    1: {
      wave1Seconds: 15,
      wave2Seconds: 7,
      wave1SpawnInterval: 1.35,
      wave2SpawnInterval: 1.05,
      midBossHp: 20,
      midBossRetreatDamage: 10,
      bossPhaseChangeHp: 15,
      bossHp: 25,
    },
    2: {
      wave1Seconds: 23,
      wave2Seconds: 12,
      wave1SpawnInterval: 1.6,
      wave2SpawnInterval: 1.25,
      midBossHp: 24,
      bossPhaseChangeHp: 18,
      bossHp: 32,
    },
    3: {
      wave1Seconds: 10,
      wave2Seconds: 3,
      wave1SpawnInterval: 999,
      wave2SpawnInterval: 999,
      midBossHp: 24,
      midBossRetreatDamage: 0,
      bossPhaseChangeHp: 20,
      bossHp: 76,
    },  },

  enemies: {
    twintail: {
      hp: 3,
      moveSpeed: 265,
    },
    visorGlasses: {
      hp: 3,
      moveSpeed: 265,
    },
    droneA: {
      hp: 1,
      moveSpeedMin: 115,
      moveSpeedMax: 170,
      firstShotMinSeconds: 0.45,
      firstShotMaxSeconds: 1.25,
      shotIntervalMinSeconds: 1.55,
      shotIntervalMaxSeconds: 2.45,
      bulletSpeed: 230,
    },
    droneB: {
      hp: 1,
      moveSpeedMin: 115,
      moveSpeedMax: 170,
      firstShotMinSeconds: 0.45,
      firstShotMaxSeconds: 1.25,
      shotIntervalMinSeconds: 1.55,
      shotIntervalMaxSeconds: 2.45,
      bulletSpeed: 230,
      radialBulletSpeed: 175,
    },
    cleaningRobot: {
      hp: 1,
      chargeSpeed: 335,
      windupSeconds: 0.72,
      zigzagSpeed: 112,
    },
    barrageRobot: {
      hp: 1,
      moveSpeedMin: 120,
      moveSpeedMax: 145,
      firstShotMinSeconds: 0.55,
      firstShotMaxSeconds: 0.55,
    },
    disciplineRobot: {
      hp: 1,
      moveSpeedMin: 135,
      moveSpeedMax: 175,
      firstShotMinSeconds: 0.45,
      firstShotMaxSeconds: 1.25,
      shotIntervalMinSeconds: 1.55,
      shotIntervalMaxSeconds: 2.45,
      jumpSeconds: 1.1,
      jumpHeight: 82,
      shinaiSpeedX: 230,
      shinaiSpeedY: 235,
      shinaiGravity: 430,
    },
    glassesEnforcer: {
      hp: 3,
      moveSpeed: 265,
      speechBubbleIntervalSeconds: 1.05,
      speechBubbleSpeed: 345,
      soloShotIntervalSeconds: 0.8,
      soloBulletSpeed: 185,
    },
    yankeeEnforcer: {
      hp: 3,
      moveSpeed: 265,
      soloShotIntervalSeconds: 0.8,
      soloBulletSpeed: 185,
    },
  },

  bosses: {
    stage1MidBoss: {
      shotIntervalSeconds: 0.62,
      bulletSpeed: 245,
    },
    stage1Boss: {
      normalShotIntervalSeconds: 0.52,
      poweredShotIntervalSeconds: 0.32,
      normalBulletSpeed: 240,
      poweredBulletSpeed: 275,
    },
    ritsuko: {
      poweredHp: 9,
      normalShotIntervalSeconds: 0.72,
      poweredShotIntervalSeconds: 0.52,
      bulletSpeed: 245,
      bulletSpeedStep: 12,
      reinforcementPauseSeconds: 1.2,
    },
    sayo: {
      shockwaveIntervalSeconds: 0.72,
      dashIntervalSeconds: 3,
      idleShotIntervalSeconds: 0.5,
      dashTelegraphSeconds: 1,
      dashTraceSeconds: 0.5,
      dashTargetPadding: 80,
    },
  },

  // Story text is data-only so it can be edited without touching game logic.
  // Each line controls the speaker name, portrait image, portrait side, and text together.
  dialogues: {
    prologue: [
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "父さんの刀が、この学園にある。……よりによって学校？" },
      { speaker: "雨宮 玄信の手紙", side: "left", portrait: "assets/dialogue-rin.png", line: "断界は、人を救うために打った。だが、救いの形を間違えれば刃は人を裁く。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "回りくどい手紙。つまり、放っておくなってことでしょ。" },
    ],
    stage1Start: [
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "校門からドローンだらけ。歓迎が機械的すぎる。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin-fired-up.png", line: "まずは一機、父さんの刀の匂いがするか確かめる。" },
    ],
    midBoss: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "朝比奈 つばめ", side: "right", portrait: "assets/dialogue-tsubame-midboss.png", line: "そこ、テニス部のコート。土足と刃物はアウトね。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "ドローンはセーフなの？ 校則、ずいぶん器用だね。" },
    ],
    boss: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "朝比奈 つばめ", side: "right", portrait: "assets/dialogue-tsubame-boss.png", line: "しつこい転校生。次は本気で返すよ。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin-fired-up.png", line: "返球はいらない。通行許可だけ置いてって。" },
    ],
    bossDefeated: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "朝比奈 つばめ", side: "right", portrait: "assets/dialogue-tsubame-defeated.png", line: "うわ、ほんとに突破するんだ……。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "このドローンの核、ただの部品じゃない。断界の欠片だ。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin-fired-up.png", line: "父さんの後始末、思ったより散らかってる。" },
    ],
    stage2Start: [
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "廊下までロボット清掃中。私もゴミ扱いかな。" },
      { speaker: "校内放送", side: "right", portrait: "assets/dialogue-ritsuko-midboss.png", line: "未登録生徒は、すみやかに指導室へ出頭してください。" },
    ],
    stage2MidBoss: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "鬼塚 律子", side: "right", portrait: "assets/dialogue-ritsuko-midboss.png", line: "刃物！ 廊下疾走！ 未登録！ 校則三倍満です！" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "点数制なの？ じゃあ満点まで付き合う。" },
    ],
    stage2Boss: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "一文字 小夜", side: "right", portrait: "assets/dialogue-sayo-boss.png", line: "あんた、御門院まで行く気？ その前に私と決着。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "前にも決着って言ってなかった？" },
      { speaker: "一文字 小夜", side: "right", portrait: "assets/dialogue-sayo-boss.png", line: "言った。足りなかった。もう一回。" },
    ],
    stage2BossDefeated: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "一文字 小夜", side: "right", portrait: "assets/dialogue-sayo-defeated.png", line: "奥に行くなら気をつけな。御門院の養子、かなり面倒だよ。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "ここまで全員面倒だったから、今さらかな。" },
    ],
    stage3Start: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "御門院 真澄", side: "right", portrait: "assets/dialogue-stage3-masumi-midboss.png", line: "ここから先は戻れない。……引き返すなら今だよ。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "忠告にしては、ずいぶん出口を塞いでる。" },
      { speaker: "御門院 真澄", side: "right", portrait: "assets/dialogue-stage3-masumi-midboss.png", line: "そう。私は親切な案内係じゃないから。" },
    ],
    stage3MidBoss: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "御門院 真澄", side: "right", portrait: "assets/dialogue-stage3-masumi-midboss.png", line: "私は養子で、実験体。どっちも好きで選んだ名前じゃない。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "だったら、どうして邪魔するの。" },
      { speaker: "御門院 真澄", side: "right", portrait: "assets/dialogue-stage3-masumi-midboss.png", line: "あなたが断界を知れば、たぶん止まれない。私みたいに。" },
    ],
    stage3Boss: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin-fired-up.png" },
      { speaker: "御門院 朔夜", side: "right", portrait: "assets/dialogue-stage3-sakuya-boss.png", line: "玄信の娘か。ずいぶん乱暴に門を叩いたものだ。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin-fired-up.png", line: "チャイムが見当たらなかったので。父さんの刀を返して。" },
      { speaker: "御門院 朔夜", side: "right", portrait: "assets/dialogue-stage3-sakuya-boss.png", line: "断界は救済だ。弱さを切れば、人は苦しまない。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin-fired-up.png", line: "苦しいって言えない人を増やしてるだけでしょ。" },
    ],
    finalBossDefeated: [
      { dialogueInitialPortraits: "left", speaker: "黒羽 凛", portrait: "assets/dialogue-rin.png" },
      { speaker: "御門院 朔夜", side: "right", portrait: "assets/dialogue-stage3-sakuya-damage.png", line: "玄信……お前の娘は、弱さを残すのか。" },
      { speaker: "黒羽 凛", side: "left", portrait: "assets/dialogue-rin.png", line: "残す。勝手に切らせない。" },
      { speaker: "御門院 真澄", side: "right", portrait: "assets/dialogue-stage3-masumi-damage.png", line: "……それ、少しだけ信じてみる。" },
    ],
  },
};
